numDelegates: 24
numCandidateDelegates: 36
numSubEpochs: 15
numSubEpochsDardanelles: 30
dardanellesHeight: 1
dardanellesOn: true
consensusScheme: "STANDALONE"
rangeQueryLimit: 100
genesis:
  account:
    initBalances:
      io10gj0e8pu6k6xgu2l6p9s8a6jmzwedfytfh4kph: "1000000000000000000000000000"
poll:
  skipManifiedCandidate: true
  voteThreshold: "100000000000000000000"
  scoreThreshold: "0"
  selfStakingThreshold: "0"
gravityChain:
  gravityChainAPIs:
    - https://mainnet.infura.io/v3/b355cae6fafc4302b106b937ee6c15af
  registerContractAddress: 0x8619a5c5232c32bae63c442b905a27ae46598566
  rewardPercentageStartHeight: 8300000
rewarding:
  numDelegatesForEpochReward: 100
  numDelegatesForFoundationBonus: 36
  foundationBonusLastEpoch: 8760
  productivityThreshold: 85
  exemptCandidatesFromEpochReward:
    - "696f726f626f746270303031"
    - "696f726f626f746270303032"
    - "696f726f626f746270303033"
    - "696f726f626f746270303034"
    - "696f726f626f746270303035"
    - "696f726f626f746270303036"
    - "696f726f626f746270303037"
    - "696f726f626f746270303038"
    - "696f726f626f746270303039"
    - "696f726f626f746270303130"
    - "696f726f626f746270303132"
    - "696f726f626f746270303131"
    - "696f726f626f746270303331"
    - "696f726f626f746270303332"
    - "696f726f626f746270303333"
    - "696f726f626f746270303334"
    - "696f726f626f746270303335"
    - "696f726f626f746270303336"
    - "696f726f626f746270303133"
    - "696f726f626f746270303134"
    - "696f726f626f746270303135"
    - "696f726f626f746270303136"
    - "696f726f626f746270303137"
    - "696f726f626f746270303138"
    - "696f726f626f746270303139"
    - "696f726f626f746270303230"
    - "696f726f626f746270303231"
    - "696f726f626f746270303232"
    - "696f726f626f746270303233"
    - "696f726f626f746270303234"
    - "696f726f626f746270303235"
    - "696f726f626f746270303236"
    - "696f726f626f746270303237"
    - "696f726f626f746270303238"
    - "696f726f626f746270303239"
    - "696f726f626f746270303330"
